spring.application.name=demo-driveflow

spring.datasource.url=jdbc:sqlserver://localhost:monster\SQLEXPRESS;databaseName=demo-driveflow;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

